namespace BlueWorm
{
	// Token: 0x0200000D RID: 13
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x0600004D RID: 77 RVA: 0x0000369C File Offset: 0x0000189C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				if (disposing && this.icontainer_0 != null)
				{
					this.icontainer_0.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x0600004E RID: 78 RVA: 0x000036E0 File Offset: 0x000018E0
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.icontainer_0 = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::BlueWorm.Form1));
			this.ContextMenuStrip1 = new global::System.Windows.Forms.ContextMenuStrip(this.icontainer_0);
			this.RunFileToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DiskToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.LinkToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RemoveClientToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.UpdateToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RansomToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.CryptToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.DecryptToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.MenuStrip1 = new global::System.Windows.Forms.MenuStrip();
			this.vmethod_10(new global::System.Windows.Forms.ContextMenuStrip(this.icontainer_0));
			this.AddPortToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.RemovePortToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.l1 = new global::System.Windows.Forms.ListView();
			this.vmethod_1(new global::System.Windows.Forms.ColumnHeader());
			this.vmethod_3(new global::System.Windows.Forms.ColumnHeader());
			this.vmethod_4(new global::System.Windows.Forms.ColumnHeader());
			this.vmethod_6(new global::System.Windows.Forms.ColumnHeader());
			this.vmethod_8(new global::System.Windows.Forms.ColumnHeader());
			this.jrIsFyuFdt(new global::System.Windows.Forms.ImageList(this.icontainer_0));
			this.vmethod_12(new global::System.Windows.Forms.ImageList(this.icontainer_0));
			this.Button2 = new global::System.Windows.Forms.Button();
			this.Button1 = new global::System.Windows.Forms.Button();
			this.Button3 = new global::System.Windows.Forms.Button();
			this.vmethod_14(new global::System.Windows.Forms.Timer(this.icontainer_0));
			this.Label1 = new global::System.Windows.Forms.Label();
			this.TextBox1 = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.ProgressBar2 = new global::System.Windows.Forms.ProgressBar();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Panel1 = new global::System.Windows.Forms.Panel();
			this.ContextMenuStrip1.SuspendLayout();
			this.vmethod_9().SuspendLayout();
			this.Panel1.SuspendLayout();
			this.SuspendLayout();
			this.ContextMenuStrip1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.RunFileToolStripMenuItem,
				this.RemoveClientToolStripMenuItem,
				this.UpdateToolStripMenuItem,
				this.RansomToolStripMenuItem
			});
			this.ContextMenuStrip1.Name = "ContextMenuStrip1";
			global::System.Windows.Forms.Control contextMenuStrip = this.ContextMenuStrip1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(214, 92);
			contextMenuStrip.Size = size;
			this.RunFileToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.DiskToolStripMenuItem,
				this.LinkToolStripMenuItem
			});
			this.RunFileToolStripMenuItem.Name = "RunFileToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem runFileToolStripMenuItem = this.RunFileToolStripMenuItem;
			size = new global::System.Drawing.Size(213, 22);
			runFileToolStripMenuItem.Size = size;
			this.RunFileToolStripMenuItem.Text = "-Run Remote Application-";
			this.DiskToolStripMenuItem.Name = "DiskToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem diskToolStripMenuItem = this.DiskToolStripMenuItem;
			size = new global::System.Drawing.Size(156, 22);
			diskToolStripMenuItem.Size = size;
			this.DiskToolStripMenuItem.Text = "-From disk-";
			this.LinkToolStripMenuItem.Name = "LinkToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem linkToolStripMenuItem = this.LinkToolStripMenuItem;
			size = new global::System.Drawing.Size(156, 22);
			linkToolStripMenuItem.Size = size;
			this.LinkToolStripMenuItem.Text = "-From internet-";
			this.RemoveClientToolStripMenuItem.BackColor = global::System.Drawing.Color.White;
			this.RemoveClientToolStripMenuItem.ForeColor = global::System.Drawing.Color.Black;
			this.RemoveClientToolStripMenuItem.Name = "RemoveClientToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem removeClientToolStripMenuItem = this.RemoveClientToolStripMenuItem;
			size = new global::System.Drawing.Size(213, 22);
			removeClientToolStripMenuItem.Size = size;
			this.RemoveClientToolStripMenuItem.Text = "-Unistall-";
			this.UpdateToolStripMenuItem.Name = "UpdateToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem updateToolStripMenuItem = this.UpdateToolStripMenuItem;
			size = new global::System.Drawing.Size(213, 22);
			updateToolStripMenuItem.Size = size;
			this.UpdateToolStripMenuItem.Text = "-Update-";
			this.RansomToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.CryptToolStripMenuItem,
				this.DecryptToolStripMenuItem
			});
			this.RansomToolStripMenuItem.Name = "RansomToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem ransomToolStripMenuItem = this.RansomToolStripMenuItem;
			size = new global::System.Drawing.Size(213, 22);
			ransomToolStripMenuItem.Size = size;
			this.RansomToolStripMenuItem.Text = "-Option Ransomware-";
			this.CryptToolStripMenuItem.ForeColor = global::System.Drawing.Color.Red;
			this.CryptToolStripMenuItem.Name = "CryptToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem cryptToolStripMenuItem = this.CryptToolStripMenuItem;
			size = new global::System.Drawing.Size(196, 22);
			cryptToolStripMenuItem.Size = size;
			this.CryptToolStripMenuItem.Text = "-Crypt Ransomware-";
			this.DecryptToolStripMenuItem.ForeColor = global::System.Drawing.Color.ForestGreen;
			this.DecryptToolStripMenuItem.Name = "DecryptToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem decryptToolStripMenuItem = this.DecryptToolStripMenuItem;
			size = new global::System.Drawing.Size(196, 22);
			decryptToolStripMenuItem.Size = size;
			this.DecryptToolStripMenuItem.Text = "-Decrypt Ransomware-";
			this.MenuStrip1.BackColor = global::System.Drawing.Color.White;
			global::System.Windows.Forms.Control menuStrip = this.MenuStrip1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(0, 0);
			menuStrip.Location = location;
			this.MenuStrip1.Name = "MenuStrip1";
			global::System.Windows.Forms.Control menuStrip2 = this.MenuStrip1;
			size = new global::System.Drawing.Size(822, 24);
			menuStrip2.Size = size;
			this.MenuStrip1.TabIndex = 1;
			this.MenuStrip1.Text = "MenuStrip1";
			this.vmethod_9().BackColor = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.vmethod_9().Items.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.AddPortToolStripMenuItem,
				this.RemovePortToolStripMenuItem
			});
			this.vmethod_9().Name = "ContextMenuStrip1";
			global::System.Windows.Forms.Control control = this.vmethod_9();
			size = new global::System.Drawing.Size(146, 48);
			control.Size = size;
			this.AddPortToolStripMenuItem.BackColor = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.AddPortToolStripMenuItem.ForeColor = global::System.Drawing.Color.Lime;
			this.AddPortToolStripMenuItem.Name = "AddPortToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem addPortToolStripMenuItem = this.AddPortToolStripMenuItem;
			size = new global::System.Drawing.Size(145, 22);
			addPortToolStripMenuItem.Size = size;
			this.AddPortToolStripMenuItem.Text = "Add Port ";
			this.RemovePortToolStripMenuItem.BackColor = global::System.Drawing.Color.FromArgb(25, 25, 25);
			this.RemovePortToolStripMenuItem.ForeColor = global::System.Drawing.Color.Lime;
			this.RemovePortToolStripMenuItem.Name = "RemovePortToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem removePortToolStripMenuItem = this.RemovePortToolStripMenuItem;
			size = new global::System.Drawing.Size(145, 22);
			removePortToolStripMenuItem.Size = size;
			this.RemovePortToolStripMenuItem.Text = "Remove Port ";
			this.l1.Anchor = (global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right);
			this.l1.BackColor = global::System.Drawing.Color.White;
			this.l1.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.l1.Columns.AddRange(new global::System.Windows.Forms.ColumnHeader[]
			{
				this.vmethod_0(),
				this.vmethod_2(),
				this.HdJsnjmybB(),
				this.vmethod_5(),
				this.vmethod_7()
			});
			this.l1.ContextMenuStrip = this.ContextMenuStrip1;
			this.l1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.l1.ForeColor = global::System.Drawing.Color.Black;
			this.l1.FullRowSelect = true;
			this.l1.GridLines = true;
			this.l1.LargeImageList = this.vmethod_13();
			global::System.Windows.Forms.Control l = this.l1;
			location = new global::System.Drawing.Point(12, 34);
			l.Location = location;
			this.l1.Name = "l1";
			global::System.Windows.Forms.Control l2 = this.l1;
			size = new global::System.Drawing.Size(798, 320);
			l2.Size = size;
			this.l1.SmallImageList = this.vmethod_13();
			this.l1.TabIndex = 6;
			this.l1.UseCompatibleStateImageBehavior = false;
			this.l1.View = global::System.Windows.Forms.View.Details;
			this.vmethod_0().Text = "Flag";
			this.vmethod_0().Width = 45;
			this.vmethod_2().Text = "Remote ip-address";
			this.vmethod_2().Width = 172;
			this.HdJsnjmybB().Text = "Bot";
			this.HdJsnjmybB().Width = 186;
			this.vmethod_5().Text = "Operation System";
			this.vmethod_5().Width = 238;
			this.vmethod_7().Text = "Country";
			this.vmethod_7().Width = 161;
			this.vmethod_13().ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("ImageList1.ImageStream");
			this.vmethod_13().TransparentColor = global::System.Drawing.Color.Transparent;
			this.vmethod_13().Images.SetKeyName(0, "1 - Copy.gif");
			this.vmethod_13().Images.SetKeyName(1, "1.gif");
			this.vmethod_13().Images.SetKeyName(2, "2.gif");
			this.vmethod_13().Images.SetKeyName(3, "3.gif");
			this.vmethod_13().Images.SetKeyName(4, "4.gif");
			this.vmethod_13().Images.SetKeyName(5, "5.gif");
			this.vmethod_13().Images.SetKeyName(6, "6.gif");
			this.vmethod_13().Images.SetKeyName(7, "7.gif");
			this.vmethod_13().Images.SetKeyName(8, "8.gif");
			this.vmethod_13().Images.SetKeyName(9, "9.gif");
			this.vmethod_13().Images.SetKeyName(10, "10.gif");
			this.vmethod_13().Images.SetKeyName(11, "11.gif");
			this.vmethod_13().Images.SetKeyName(12, "12.gif");
			this.vmethod_13().Images.SetKeyName(13, "13.gif");
			this.vmethod_13().Images.SetKeyName(14, "14.gif");
			this.vmethod_13().Images.SetKeyName(15, "15.gif");
			this.vmethod_13().Images.SetKeyName(16, "16.gif");
			this.vmethod_13().Images.SetKeyName(17, "17.gif");
			this.vmethod_13().Images.SetKeyName(18, "18.gif");
			this.vmethod_13().Images.SetKeyName(19, "19.gif");
			this.vmethod_13().Images.SetKeyName(20, "20.gif");
			this.vmethod_13().Images.SetKeyName(21, "21.gif");
			this.vmethod_13().Images.SetKeyName(22, "22.gif");
			this.vmethod_13().Images.SetKeyName(23, "23.gif");
			this.vmethod_13().Images.SetKeyName(24, "24.gif");
			this.vmethod_13().Images.SetKeyName(25, "25.gif");
			this.vmethod_13().Images.SetKeyName(26, "26.gif");
			this.vmethod_13().Images.SetKeyName(27, "27.gif");
			this.vmethod_13().Images.SetKeyName(28, "28.gif");
			this.vmethod_13().Images.SetKeyName(29, "29.gif");
			this.vmethod_13().Images.SetKeyName(30, "30.gif");
			this.vmethod_13().Images.SetKeyName(31, "31.gif");
			this.vmethod_13().Images.SetKeyName(32, "32.gif");
			this.vmethod_13().Images.SetKeyName(33, "33.gif");
			this.vmethod_13().Images.SetKeyName(34, "34.gif");
			this.vmethod_13().Images.SetKeyName(35, "35.gif");
			this.vmethod_13().Images.SetKeyName(36, "36.gif");
			this.vmethod_13().Images.SetKeyName(37, "37.gif");
			this.vmethod_13().Images.SetKeyName(38, "38.gif");
			this.vmethod_13().Images.SetKeyName(39, "39.gif");
			this.vmethod_13().Images.SetKeyName(40, "40.gif");
			this.vmethod_13().Images.SetKeyName(41, "41.gif");
			this.vmethod_13().Images.SetKeyName(42, "42.gif");
			this.vmethod_13().Images.SetKeyName(43, "43.gif");
			this.vmethod_13().Images.SetKeyName(44, "44.gif");
			this.vmethod_13().Images.SetKeyName(45, "45.gif");
			this.vmethod_13().Images.SetKeyName(46, "46.gif");
			this.vmethod_13().Images.SetKeyName(47, "47.gif");
			this.vmethod_13().Images.SetKeyName(48, "48.gif");
			this.vmethod_13().Images.SetKeyName(49, "49.gif");
			this.vmethod_13().Images.SetKeyName(50, "50.gif");
			this.vmethod_13().Images.SetKeyName(51, "51.gif");
			this.vmethod_13().Images.SetKeyName(52, "52.gif");
			this.vmethod_13().Images.SetKeyName(53, "53.gif");
			this.vmethod_13().Images.SetKeyName(54, "54.gif");
			this.vmethod_13().Images.SetKeyName(55, "55.gif");
			this.vmethod_13().Images.SetKeyName(56, "56.gif");
			this.vmethod_13().Images.SetKeyName(57, "57.gif");
			this.vmethod_13().Images.SetKeyName(58, "58.gif");
			this.vmethod_13().Images.SetKeyName(59, "59.gif");
			this.vmethod_13().Images.SetKeyName(60, "60.gif");
			this.vmethod_13().Images.SetKeyName(61, "61.gif");
			this.vmethod_13().Images.SetKeyName(62, "62.gif");
			this.vmethod_13().Images.SetKeyName(63, "63.gif");
			this.vmethod_13().Images.SetKeyName(64, "64.gif");
			this.vmethod_13().Images.SetKeyName(65, "65.gif");
			this.vmethod_13().Images.SetKeyName(66, "66.gif");
			this.vmethod_13().Images.SetKeyName(67, "67.gif");
			this.vmethod_13().Images.SetKeyName(68, "68.gif");
			this.vmethod_13().Images.SetKeyName(69, "69.gif");
			this.vmethod_13().Images.SetKeyName(70, "70.gif");
			this.vmethod_13().Images.SetKeyName(71, "71.gif");
			this.vmethod_13().Images.SetKeyName(72, "72.gif");
			this.vmethod_13().Images.SetKeyName(73, "73.gif");
			this.vmethod_13().Images.SetKeyName(74, "74.gif");
			this.vmethod_13().Images.SetKeyName(75, "75.gif");
			this.vmethod_13().Images.SetKeyName(76, "76.gif");
			this.vmethod_13().Images.SetKeyName(77, "77.gif");
			this.vmethod_13().Images.SetKeyName(78, "78.gif");
			this.vmethod_13().Images.SetKeyName(79, "79.gif");
			this.vmethod_13().Images.SetKeyName(80, "80.gif");
			this.vmethod_13().Images.SetKeyName(81, "81.gif");
			this.vmethod_13().Images.SetKeyName(82, "82.gif");
			this.vmethod_13().Images.SetKeyName(83, "83.gif");
			this.vmethod_13().Images.SetKeyName(84, "84.gif");
			this.vmethod_13().Images.SetKeyName(85, "85.gif");
			this.vmethod_13().Images.SetKeyName(86, "86.gif");
			this.vmethod_13().Images.SetKeyName(87, "87.gif");
			this.vmethod_13().Images.SetKeyName(88, "88.gif");
			this.vmethod_13().Images.SetKeyName(89, "89.gif");
			this.vmethod_13().Images.SetKeyName(90, "90.gif");
			this.vmethod_13().Images.SetKeyName(91, "91.gif");
			this.vmethod_13().Images.SetKeyName(92, "92.gif");
			this.vmethod_13().Images.SetKeyName(93, "93.gif");
			this.vmethod_13().Images.SetKeyName(94, "94.gif");
			this.vmethod_13().Images.SetKeyName(95, "95.gif");
			this.vmethod_13().Images.SetKeyName(96, "96.gif");
			this.vmethod_13().Images.SetKeyName(97, "97.gif");
			this.vmethod_13().Images.SetKeyName(98, "98.gif");
			this.vmethod_13().Images.SetKeyName(99, "99.gif");
			this.vmethod_13().Images.SetKeyName(100, "100.gif");
			this.vmethod_13().Images.SetKeyName(101, "101.gif");
			this.vmethod_13().Images.SetKeyName(102, "102.gif");
			this.vmethod_13().Images.SetKeyName(103, "103.gif");
			this.vmethod_13().Images.SetKeyName(104, "104.gif");
			this.vmethod_13().Images.SetKeyName(105, "105.gif");
			this.vmethod_13().Images.SetKeyName(106, "106.gif");
			this.vmethod_13().Images.SetKeyName(107, "107.gif");
			this.vmethod_13().Images.SetKeyName(108, "108.gif");
			this.vmethod_13().Images.SetKeyName(109, "109.gif");
			this.vmethod_13().Images.SetKeyName(110, "110.gif");
			this.vmethod_13().Images.SetKeyName(111, "111.gif");
			this.vmethod_13().Images.SetKeyName(112, "112.gif");
			this.vmethod_13().Images.SetKeyName(113, "113.gif");
			this.vmethod_13().Images.SetKeyName(114, "114.gif");
			this.vmethod_13().Images.SetKeyName(115, "115.gif");
			this.vmethod_13().Images.SetKeyName(116, "116.gif");
			this.vmethod_13().Images.SetKeyName(117, "117.gif");
			this.vmethod_13().Images.SetKeyName(118, "118.gif");
			this.vmethod_13().Images.SetKeyName(119, "119.gif");
			this.vmethod_13().Images.SetKeyName(120, "120.gif");
			this.vmethod_13().Images.SetKeyName(121, "121.gif");
			this.vmethod_13().Images.SetKeyName(122, "122.gif");
			this.vmethod_13().Images.SetKeyName(123, "123.gif");
			this.vmethod_13().Images.SetKeyName(124, "124.gif");
			this.vmethod_13().Images.SetKeyName(125, "125.gif");
			this.vmethod_13().Images.SetKeyName(126, "126.gif");
			this.vmethod_13().Images.SetKeyName(127, "127.gif");
			this.vmethod_13().Images.SetKeyName(128, "128.gif");
			this.vmethod_13().Images.SetKeyName(129, "129.gif");
			this.vmethod_13().Images.SetKeyName(130, "130.gif");
			this.vmethod_13().Images.SetKeyName(131, "131.gif");
			this.vmethod_13().Images.SetKeyName(132, "132.gif");
			this.vmethod_13().Images.SetKeyName(133, "133.gif");
			this.vmethod_13().Images.SetKeyName(134, "134.gif");
			this.vmethod_13().Images.SetKeyName(135, "135.gif");
			this.vmethod_13().Images.SetKeyName(136, "136.gif");
			this.vmethod_13().Images.SetKeyName(137, "137.gif");
			this.vmethod_13().Images.SetKeyName(138, "138.gif");
			this.vmethod_13().Images.SetKeyName(139, "139.gif");
			this.vmethod_13().Images.SetKeyName(140, "140.gif");
			this.vmethod_13().Images.SetKeyName(141, "141.gif");
			this.vmethod_13().Images.SetKeyName(142, "142.gif");
			this.vmethod_13().Images.SetKeyName(143, "143.gif");
			this.vmethod_13().Images.SetKeyName(144, "144.gif");
			this.vmethod_13().Images.SetKeyName(145, "145.gif");
			this.vmethod_13().Images.SetKeyName(146, "146.gif");
			this.vmethod_13().Images.SetKeyName(147, "147.gif");
			this.vmethod_13().Images.SetKeyName(148, "148.gif");
			this.vmethod_13().Images.SetKeyName(149, "149.gif");
			this.vmethod_13().Images.SetKeyName(150, "150.gif");
			this.vmethod_13().Images.SetKeyName(151, "151.gif");
			this.vmethod_13().Images.SetKeyName(152, "152.gif");
			this.vmethod_13().Images.SetKeyName(153, "153.gif");
			this.vmethod_13().Images.SetKeyName(154, "154.gif");
			this.vmethod_13().Images.SetKeyName(155, "155.gif");
			this.vmethod_13().Images.SetKeyName(156, "156.gif");
			this.vmethod_13().Images.SetKeyName(157, "157.gif");
			this.vmethod_13().Images.SetKeyName(158, "158.gif");
			this.vmethod_13().Images.SetKeyName(159, "159.gif");
			this.vmethod_13().Images.SetKeyName(160, "160.gif");
			this.vmethod_13().Images.SetKeyName(161, "161.gif");
			this.vmethod_13().Images.SetKeyName(162, "162.gif");
			this.vmethod_13().Images.SetKeyName(163, "163.gif");
			this.vmethod_13().Images.SetKeyName(164, "164.gif");
			this.vmethod_13().Images.SetKeyName(165, "165.gif");
			this.vmethod_13().Images.SetKeyName(166, "166.gif");
			this.vmethod_13().Images.SetKeyName(167, "167.gif");
			this.vmethod_13().Images.SetKeyName(168, "168.gif");
			this.vmethod_13().Images.SetKeyName(169, "169.gif");
			this.vmethod_13().Images.SetKeyName(170, "170.gif");
			this.vmethod_13().Images.SetKeyName(171, "171.gif");
			this.vmethod_13().Images.SetKeyName(172, "172.gif");
			this.vmethod_13().Images.SetKeyName(173, "173.gif");
			this.vmethod_13().Images.SetKeyName(174, "174.gif");
			this.vmethod_13().Images.SetKeyName(175, "175.gif");
			this.vmethod_13().Images.SetKeyName(176, "176.gif");
			this.vmethod_13().Images.SetKeyName(177, "177.gif");
			this.vmethod_13().Images.SetKeyName(178, "178.gif");
			this.vmethod_13().Images.SetKeyName(179, "179.gif");
			this.vmethod_13().Images.SetKeyName(180, "180.gif");
			this.vmethod_13().Images.SetKeyName(181, "181.gif");
			this.vmethod_13().Images.SetKeyName(182, "182.gif");
			this.vmethod_13().Images.SetKeyName(183, "183.gif");
			this.vmethod_13().Images.SetKeyName(184, "184.gif");
			this.vmethod_13().Images.SetKeyName(185, "185.gif");
			this.vmethod_13().Images.SetKeyName(186, "186.gif");
			this.vmethod_13().Images.SetKeyName(187, "187.gif");
			this.vmethod_13().Images.SetKeyName(188, "188.gif");
			this.vmethod_13().Images.SetKeyName(189, "189.gif");
			this.vmethod_13().Images.SetKeyName(190, "190.gif");
			this.vmethod_13().Images.SetKeyName(191, "191.gif");
			this.vmethod_13().Images.SetKeyName(192, "192.gif");
			this.vmethod_13().Images.SetKeyName(193, "193.gif");
			this.vmethod_13().Images.SetKeyName(194, "194.gif");
			this.vmethod_13().Images.SetKeyName(195, "195.gif");
			this.vmethod_13().Images.SetKeyName(196, "196.gif");
			this.vmethod_13().Images.SetKeyName(197, "197.gif");
			this.vmethod_13().Images.SetKeyName(198, "198.gif");
			this.vmethod_13().Images.SetKeyName(199, "199.gif");
			this.vmethod_13().Images.SetKeyName(200, "200.gif");
			this.vmethod_13().Images.SetKeyName(201, "201.gif");
			this.vmethod_13().Images.SetKeyName(202, "202.gif");
			this.vmethod_13().Images.SetKeyName(203, "203.gif");
			this.vmethod_13().Images.SetKeyName(204, "204.gif");
			this.vmethod_13().Images.SetKeyName(205, "205.gif");
			this.vmethod_13().Images.SetKeyName(206, "206.gif");
			this.vmethod_13().Images.SetKeyName(207, "207.jpg");
			this.vmethod_13().Images.SetKeyName(208, "208.gif");
			this.vmethod_13().Images.SetKeyName(209, "209.gif");
			this.vmethod_13().Images.SetKeyName(210, "210.gif");
			this.vmethod_13().Images.SetKeyName(211, "211.gif");
			this.vmethod_13().Images.SetKeyName(212, "212.gif");
			this.vmethod_13().Images.SetKeyName(213, "213.gif");
			this.vmethod_13().Images.SetKeyName(214, "214.gif");
			this.vmethod_13().Images.SetKeyName(215, "215.gif");
			this.vmethod_13().Images.SetKeyName(216, "216.gif");
			this.vmethod_13().Images.SetKeyName(217, "217.gif");
			this.vmethod_13().Images.SetKeyName(218, "218.gif");
			this.vmethod_13().Images.SetKeyName(219, "219.gif");
			this.vmethod_13().Images.SetKeyName(220, "220.gif");
			this.vmethod_13().Images.SetKeyName(221, "221.gif");
			this.vmethod_13().Images.SetKeyName(222, "222.gif");
			this.vmethod_13().Images.SetKeyName(223, "223.gif");
			this.vmethod_13().Images.SetKeyName(224, "224.gif");
			this.vmethod_13().Images.SetKeyName(225, "225.gif");
			this.vmethod_13().Images.SetKeyName(226, "226.gif");
			this.vmethod_13().Images.SetKeyName(227, "227.gif");
			this.vmethod_13().Images.SetKeyName(228, "228.gif");
			this.vmethod_13().Images.SetKeyName(229, "229.gif");
			this.vmethod_13().Images.SetKeyName(230, "230.gif");
			this.vmethod_13().Images.SetKeyName(231, "231.gif");
			this.vmethod_13().Images.SetKeyName(232, "232.gif");
			this.vmethod_13().Images.SetKeyName(233, "233.gif");
			this.vmethod_13().Images.SetKeyName(234, "234.gif");
			this.vmethod_13().Images.SetKeyName(235, "235.gif");
			this.vmethod_13().Images.SetKeyName(236, "236.gif");
			this.vmethod_13().Images.SetKeyName(237, "237.gif");
			this.vmethod_13().Images.SetKeyName(238, "238.gif");
			this.vmethod_13().Images.SetKeyName(239, "239.gif");
			this.vmethod_13().Images.SetKeyName(240, "240.gif");
			this.vmethod_13().Images.SetKeyName(241, "241.gif");
			this.vmethod_13().Images.SetKeyName(242, "basic.png");
			this.vmethod_13().Images.SetKeyName(243, "connections.png");
			this.vmethod_13().Images.SetKeyName(244, "group.png");
			this.vmethod_13().Images.SetKeyName(245, "misc.png");
			this.vmethod_13().Images.SetKeyName(246, "user.png");
			this.vmethod_13().Images.SetKeyName(247, "user_gray.png");
			this.vmethod_11().ImageStream = (global::System.Windows.Forms.ImageListStreamer)componentResourceManager.GetObject("ImageList2.ImageStream");
			this.vmethod_11().TransparentColor = global::System.Drawing.Color.Transparent;
			this.vmethod_11().Images.SetKeyName(0, "1.png");
			this.Button2.BackColor = global::System.Drawing.Color.White;
			this.Button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button2.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button = this.Button2;
			location = new global::System.Drawing.Point(16, 3);
			button.Location = location;
			this.Button2.Name = "Button2";
			global::System.Windows.Forms.Control button2 = this.Button2;
			size = new global::System.Drawing.Size(59, 21);
			button2.Size = size;
			this.Button2.TabIndex = 13;
			this.Button2.Text = "Listen";
			this.Button2.UseVisualStyleBackColor = false;
			this.Button1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Button1.BackColor = global::System.Drawing.Color.White;
			this.Button1.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button1.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button3 = this.Button1;
			location = new global::System.Drawing.Point(12, 358);
			button3.Location = location;
			this.Button1.Name = "Button1";
			global::System.Windows.Forms.Control button4 = this.Button1;
			size = new global::System.Drawing.Size(122, 22);
			button4.Size = size;
			this.Button1.TabIndex = 14;
			this.Button1.Text = "Builder";
			this.Button1.UseVisualStyleBackColor = false;
			this.Button3.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left);
			this.Button3.BackColor = global::System.Drawing.Color.White;
			this.Button3.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.Button3.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control button5 = this.Button3;
			location = new global::System.Drawing.Point(140, 358);
			button5.Location = location;
			this.Button3.Name = "Button3";
			global::System.Windows.Forms.Control button6 = this.Button3;
			size = new global::System.Drawing.Size(122, 22);
			button6.Size = size;
			this.Button3.TabIndex = 15;
			this.Button3.Text = "About";
			this.Button3.UseVisualStyleBackColor = false;
			this.umesxYcZi0().Enabled = true;
			this.Label1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.Label1.AutoSize = true;
			this.Label1.ForeColor = global::System.Drawing.Color.FromArgb(0, 192, 0);
			global::System.Windows.Forms.Control label = this.Label1;
			location = new global::System.Drawing.Point(681, 367);
			label.Location = location;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label2 = this.Label1;
			size = new global::System.Drawing.Size(0, 13);
			label2.Size = size;
			this.Label1.TabIndex = 16;
			global::System.Windows.Forms.Control textBox = this.TextBox1;
			location = new global::System.Drawing.Point(119, 3);
			textBox.Location = location;
			this.TextBox1.Multiline = true;
			this.TextBox1.Name = "TextBox1";
			global::System.Windows.Forms.Control textBox2 = this.TextBox1;
			size = new global::System.Drawing.Size(63, 20);
			textBox2.Size = size;
			this.TextBox1.TabIndex = 17;
			this.TextBox1.Text = "9091";
			this.Label2.AutoSize = true;
			this.Label2.ForeColor = global::System.Drawing.Color.Red;
			global::System.Windows.Forms.Control label3 = this.Label2;
			location = new global::System.Drawing.Point(81, 4);
			label3.Location = location;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label4 = this.Label2;
			size = new global::System.Drawing.Size(32, 13);
			label4.Size = size;
			this.Label2.TabIndex = 18;
			this.Label2.Text = "Port :";
			global::System.Windows.Forms.Control progressBar = this.ProgressBar2;
			location = new global::System.Drawing.Point(188, 10);
			progressBar.Location = location;
			this.ProgressBar2.Name = "ProgressBar2";
			global::System.Windows.Forms.Control progressBar2 = this.ProgressBar2;
			size = new global::System.Drawing.Size(65, 10);
			progressBar2.Size = size;
			this.ProgressBar2.TabIndex = 26;
			this.Label3.AutoSize = true;
			this.Label3.ForeColor = global::System.Drawing.Color.FromArgb(0, 0, 192);
			global::System.Windows.Forms.Control label5 = this.Label3;
			location = new global::System.Drawing.Point(270, 7);
			label5.Location = location;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label6 = this.Label3;
			size = new global::System.Drawing.Size(0, 13);
			label6.Size = size;
			this.Label3.TabIndex = 27;
			this.Panel1.Controls.Add(this.Button2);
			this.Panel1.Controls.Add(this.Label3);
			this.Panel1.Controls.Add(this.TextBox1);
			this.Panel1.Controls.Add(this.Label2);
			this.Panel1.Controls.Add(this.ProgressBar2);
			global::System.Windows.Forms.Control panel = this.Panel1;
			location = new global::System.Drawing.Point(12, 0);
			panel.Location = location;
			this.Panel1.Name = "Panel1";
			global::System.Windows.Forms.Control panel2 = this.Panel1;
			size = new global::System.Drawing.Size(798, 29);
			panel2.Size = size;
			this.Panel1.TabIndex = 28;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.White;
			size = new global::System.Drawing.Size(822, 386);
			this.ClientSize = size;
			this.Controls.Add(this.Panel1);
			this.Controls.Add(this.Label1);
			this.Controls.Add(this.Button3);
			this.Controls.Add(this.Button1);
			this.Controls.Add(this.l1);
			this.Controls.Add(this.MenuStrip1);
			this.ForeColor = global::System.Drawing.Color.Black;
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MainMenuStrip = this.MenuStrip1;
			this.Name = "Form1";
			this.Text = "Sarmat-worm V1.2";
			this.ContextMenuStrip1.ResumeLayout(false);
			this.vmethod_9().ResumeLayout(false);
			this.Panel1.ResumeLayout(false);
			this.Panel1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400001B RID: 27
		private global::System.ComponentModel.IContainer icontainer_0;
	}
}
